# Site settings
title: AREC 615
subtitle: Optimization Methods for Applied Economics
description: |
    This course provides graduate students in agricultural, environmental, and resource economics with a rigorous introduction to optimization methods used in economic modeling and policy analysis. Emphasizing both theory and computation, the course covers linear and nonlinear programming, dynamic optimization, and numerical methods essential for solving complex economic problems. Students will learn to formulate, solve, and interpret optimization models using R, with applications drawn from land use planning, natural resource management, agricultural production, and environmental policy design. The course equips students with practical modeling skills and analytical tools that support evidence-based research and decision-making in applied economics.

baseurl: "/arec-615" # the subpath of your site, e.g. /blog/
url: "https://jbayham.github.io" # the base hostname & protocol for your site
syllabus: "/syllabus"
githubdir: "jbayham/arec-615"

# Author/user information
email: jbayham@colostate.edu
#twitter_username: stevenvmiller
github_username:  jbayham
# authorurl: "https://sites.google.com/site/judebayham/home"
# address: |
#     Department of Political Science
#     232 Brackett Hall
#     Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
